export { createKb, addEntry, searchEntries, updateEntry, exportKb, loadKb, saveKb } from './knowledge-store.js';
export type { KbEntry, KnowledgeBase } from './knowledge-store.js';
export * from './schemas.js';
import { createKb, addEntry, searchEntries, updateEntry, exportKb } from './knowledge-store.js';
import type { MCPToolDefinition } from '../plan-first/index.js';
import type { KbCreateInput, KbAddInput, KbSearchInput, KbUpdateInput, KbExportInput } from './schemas.js';

export const knowledgeTools: MCPToolDefinition<unknown, unknown>[] = [
  { name: 'kb_create', description: 'Create a new domain knowledge base for storing structured knowledge entries', inputSchema: { type: 'object', properties: { name: { type: 'string' }, domain: { type: 'string' }, description: { type: 'string' } }, required: ['name', 'domain'] }, handler: (i) => { const inp = i as KbCreateInput; const kb = createKb(inp.name, inp.domain, inp.description); return Promise.resolve({ kb_id: kb.kb_id, name: kb.name, domain: kb.domain, entry_count: kb.entries.length, created_at: kb.created_at }); } },
  { name: 'kb_add', description: 'Add a knowledge entry to a knowledge base', inputSchema: { type: 'object', properties: { kb_id: { type: 'string' }, title: { type: 'string' }, content: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } }, source: { type: 'string' } }, required: ['kb_id', 'title', 'content'] }, handler: (i) => Promise.resolve(addEntry((i as KbAddInput).kb_id, (i as KbAddInput).title, (i as KbAddInput).content, (i as KbAddInput).tags, (i as KbAddInput).source)) },
  { name: 'kb_search', description: 'Search knowledge base entries by keyword (semantic search ready)', inputSchema: { type: 'object', properties: { kb_id: { type: 'string' }, query: { type: 'string' }, limit: { type: 'number' } }, required: ['kb_id', 'query'] }, handler: (i) => { const inp = i as KbSearchInput; return Promise.resolve({ results: searchEntries(inp.kb_id, inp.query, inp.limit || 5), total: searchEntries(inp.kb_id, inp.query, 100).length }); } },
  { name: 'kb_update', description: 'Update an existing knowledge base entry', inputSchema: { type: 'object', properties: { kb_id: { type: 'string' }, entry_id: { type: 'string' }, title: { type: 'string' }, content: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } }, required: ['kb_id', 'entry_id'] }, handler: (i) => Promise.resolve(updateEntry((i as KbUpdateInput).kb_id, (i as KbUpdateInput).entry_id, { title: (i as KbUpdateInput).title, content: (i as KbUpdateInput).content, tags: (i as KbUpdateInput).tags })) },
  { name: 'kb_export', description: 'Export knowledge base as training data (jsonl, csv, or finetune format)', inputSchema: { type: 'object', properties: { kb_id: { type: 'string' }, format: { type: 'string', enum: ['jsonl', 'csv', 'finetune'] } }, required: ['kb_id'] }, handler: (i) => { const inp = i as KbExportInput; const data = exportKb(inp.kb_id, (inp.format as any) || 'jsonl'); const lines = data.split('\n').filter(Boolean); return Promise.resolve({ data, format: inp.format || 'jsonl', entry_count: lines.length }); } },
];
